services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nirbhor_backend_dev
    tty: true # ← allocates a pseudo-TTY, loguru detects it and enables colors
    stdin_open: true   # ← keeps stdin open (needed alongside tty)
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - FORCE_COLOR=1  # force docker to color output
      - TERM=xterm-256color # set terminal type

  db:
    image: postgis/postgis:16-3.4
    container_name: nirbhor_db_dev_with_postgis
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nirbhor_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: nirbhor_pgadmin_dev
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - db


volumes:
  postgres_data: