"""created spatial_index for provider base location

Revision ID: 01ace21bc136
Revises: 1a02de75716d
Create Date: 2026-07-15 10:41:34.592245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ace21bc136'
down_revision: Union[str, Sequence[str], None] = '1a02de75716d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_provider_profiles_base_location', 'provider_profiles', ['base_location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_provider_profiles_base_location', table_name='provider_profiles', postgresql_using='gist')
    # ### end Alembic commands ###
