"""created urgent broadcast model and made relationship with user model

Revision ID: 0d326cc0faff
Revises: 393dce9f9959
Create Date: 2026-05-23 11:41:12.900306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '0d326cc0faff'
down_revision: Union[str, Sequence[str], None] = '393dce9f9959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urgent_broadcasts',
    sa.Column('seeker_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.Enum('broadcasting', 'claimed', 'expired', name='broadcast_status', native_enum=False), server_default='broadcasting', nullable=False),
    sa.Column('claimed_by_provider_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_provider_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urgent_broadcasts_id'), 'urgent_broadcasts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urgent_broadcasts_id'), table_name='urgent_broadcasts')
    op.drop_table('urgent_broadcasts')
    # ### end Alembic commands ###
