"""added ai_summary_generation_time in ProviderProfile table

Revision ID: 1a02de75716d
Revises: dcb80d4531b7
Create Date: 2026-07-13 09:37:31.863542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a02de75716d'
down_revision: Union[str, Sequence[str], None] = 'dcb80d4531b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('ai_summary_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'ai_summary_generated_at')
    # ### end Alembic commands ###
