"""added 3 column for public id

Revision ID: 1e40abd213da
Revises: ec8feeca98b1
Create Date: 2026-06-04 16:43:11.485185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e40abd213da'
down_revision: Union[str, Sequence[str], None] = 'ec8feeca98b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('photo_public_id', sa.String(), nullable=True))
    op.add_column('provider_profiles', sa.Column('nid_front_public_id', sa.String(), nullable=True))
    op.add_column('provider_profiles', sa.Column('nid_back_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'nid_back_public_id')
    op.drop_column('provider_profiles', 'nid_front_public_id')
    op.drop_column('provider_profiles', 'photo_public_id')
    # ### end Alembic commands ###
