"""removed name_en, name_bn from provider profile table

Revision ID: 3dd878ff2914
Revises: 3f7ef0ba7121
Create Date: 2026-06-02 14:22:58.501042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd878ff2914'
down_revision: Union[str, Sequence[str], None] = '3f7ef0ba7121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'name_en')
    op.drop_column('provider_profiles', 'name_bn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('name_bn', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('provider_profiles', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
