"""created reviewee model

Revision ID: 3f7ef0ba7121
Revises: b9a13cd5a91a
Create Date: 2026-05-23 13:10:40.450374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7ef0ba7121'
down_revision: Union[str, Sequence[str], None] = 'b9a13cd5a91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
                    sa.Column('booking_id', sa.UUID(), nullable=False),
                    sa.Column('reviewer_id', sa.UUID(), nullable=False),
                    sa.Column('reviewee_id', sa.UUID(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.String(), nullable=True),
                    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.CheckConstraint('rating >= 1 AND rating <= 5',
                                       name='ck_review_rating_range'),
                    sa.ForeignKeyConstraint(
                        ['booking_id'], ['bookings.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['reviewee_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['reviewer_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('booking_id', 'reviewer_id',
                                        name='uq_review_booking_reviewer')
                    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)

    # manually adding the following code to add check constraint
    op.execute("""
    CREATE OR REPLACE FUNCTION check_booking_completable()
    RETURNS TRIGGER AS $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM bookings
            WHERE id = NEW.booking_id
              AND status = 'completed'
              AND confirmed_at IS NOT NULL
        ) THEN
            RAISE EXCEPTION 'Review only allowed for completed and confirmed bookings';
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER enforce_review_eligibility
    BEFORE INSERT ON reviews
    FOR EACH ROW EXECUTE FUNCTION check_booking_completable();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS enforce_review_eligibility ON reviews")
    op.execute("DROP FUNCTION IF EXISTS check_booking_completable")
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table("reviews")
    # ### end Alembic commands ###
