"""created FCM Token model and added relationship with user model

Revision ID: 4406dc965911
Revises: 8e8bff99c01c
Create Date: 2026-05-22 16:45:29.117922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4406dc965911'
down_revision: Union[str, Sequence[str], None] = '8e8bff99c01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_tokens',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('token', sa.String(), nullable=True),
                    sa.Column('device_type', sa.Enum('android', 'ios', 'web', name='device_type',
                                                     native_enum=False), server_default='android', nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_fcm_tokens_id'),
                    'fcm_tokens', ['id'], unique=False)
    op.drop_index(
        op.f('idx_provider_profiles_base_location'),
        table_name='provider_profiles',
        postgresql_using='gist',
        if_exists=True  # 👈 This tells Postgres: "If it's not there, skip without crashing"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_provider_profiles_base_location'), 'provider_profiles', [
                    'base_location'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_fcm_tokens_id'), table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    # ### end Alembic commands ###
