"""added preferred language column for users with default NULL. Null will be removed later

Revision ID: 5310b0620353
Revises: c9f5f2601a85
Create Date: 2026-07-07 20:56:38.844674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5310b0620353'
down_revision: Union[str, Sequence[str], None] = 'c9f5f2601a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_lang', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_lang')
    # ### end Alembic commands ###
