"""added under_investigation report status in report model

Revision ID: 5bff9bde1538
Revises: 9f5e3f7b585a
Create Date: 2026-06-30 15:57:11.240011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bff9bde1538'
down_revision: Union[str, Sequence[str], None] = '9f5e3f7b585a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_reports', 'status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('pending', 'under_investigation', 'reviewed', 'action_taken', name='report_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_reports', 'status',
               existing_type=sa.Enum('pending', 'under_investigation', 'reviewed', 'action_taken', name='report_status', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
