"""added location_updated_at column

Revision ID: 5f0bed00ddd7
Revises: 9c5703cbb7c5
Create Date: 2026-06-03 14:38:13.726725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0bed00ddd7'
down_revision: Union[str, Sequence[str], None] = '9c5703cbb7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'location_updated_at')
    # ### end Alembic commands ###
