"""created provider_profile model

Revision ID: 8fbeaebe09c3
Revises: 45dd5d36b27e
Create Date: 2026-05-22 12:24:18.135321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fbeaebe09c3'
down_revision: Union[str, Sequence[str], None] = '45dd5d36b27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_profiles',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('name_en', sa.String(), nullable=False),
                    sa.Column('name_bn', sa.String(), nullable=False),
                    sa.Column('photo_url', sa.String(), nullable=True),
                    sa.Column('nid_url', sa.String(), nullable=True),
                    sa.Column('verification_level', sa.Enum('BASIC', 'VERIFIED', 'TRUSTED',
                                                            name='verification_level', native_enum=False), server_default='BASIC', nullable=False),
                    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED',
                                                             name='verification_status', native_enum=False), server_default='PENDING', nullable=False),
                    sa.Column('verification_rejection_reason',
                              sa.String(), nullable=True),
                    sa.Column('base_location', Geometry(geometry_type='POINT', srid=4326, dimension=2,
                                                        from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
                    sa.Column('working_radius_km',
                              sa.Integer(), nullable=False),
                    sa.Column('has_smartphone', sa.Boolean(), nullable=False),
                    sa.Column('is_available', sa.Boolean(), nullable=False),
                    sa.Column('average_rating', sa.Float(), nullable=True),
                    sa.Column('warning_status', sa.Boolean(), nullable=False),
                    sa.Column('ai_review_summary_en',
                              sa.String(), nullable=True),
                    sa.Column('ai_review_summary_bn',
                              sa.String(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'id')
                    )
    # op.create_index('idx_provider_profiles_base_location', 'provider_profiles', ['base_location'], unique=False, postgresql_using='gist')
    # replaced the above line with the one below to fix migration issue
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_provider_profiles_base_location 
        ON provider_profiles USING gist (base_location)
    """)
    op.create_index(op.f('ix_provider_profiles_id'),
                    'provider_profiles', ['id'], unique=False)
    op.alter_column('users', 'last_active_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'last_active_at',
    #                 existing_type=postgresql.TIMESTAMP(timezone=True),
    #                 nullable=False)
    # op.drop_index(op.f('ix_provider_profiles_id'),
    #               table_name='provider_profiles')
    # op.drop_index('idx_provider_profiles_base_location',
    #               table_name='provider_profiles', postgresql_using='gist')
    # op.drop_table('provider_profiles')
    # replaced the above line with the one below to fix migration issue
    op.execute("DROP INDEX IF EXISTS idx_provider_profiles_base_location")
    op.drop_table('provider_profiles')
    # ### end Alembic commands ###
