"""added name_en, name_bn in user table

Revision ID: 9c5703cbb7c5
Revises: 3dd878ff2914
Create Date: 2026-06-02 14:24:04.784205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5703cbb7c5'
down_revision: Union[str, Sequence[str], None] = '3dd878ff2914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_en', sa.String(), nullable=False))
    op.add_column('users', sa.Column('name_bn', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name_bn')
    op.drop_column('users', 'name_en')
    # ### end Alembic commands ###
