"""added not_initiated verification status as default

Revision ID: 9f5e3f7b585a
Revises: ca688c0d6266
Create Date: 2026-06-30 13:19:42.637275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5e3f7b585a'
down_revision: Union[str, Sequence[str], None] = 'ca688c0d6266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider_profiles', 'verification_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('not_initiated', 'pending', 'approved', 'rejected', name='verification_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider_profiles', 'verification_status',
               existing_type=sa.Enum('not_initiated', 'pending', 'approved', 'rejected', name='verification_status', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
