"""fixed fcm token models relation with user

Revision ID: b9a13cd5a91a
Revises: dda011754572
Create Date: 2026-05-23 12:12:47.764863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a13cd5a91a'
down_revision: Union[str, Sequence[str], None] = 'dda011754572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fcm_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'fcm_tokens', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fcm_tokens', type_='unique')
    op.alter_column('fcm_tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
