"""added composite indexes on booking, user report, user model

Revision ID: c9f5f2601a85
Revises: 5bff9bde1538
Create Date: 2026-07-01 14:47:41.794883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f5f2601a85'
down_revision: Union[str, Sequence[str], None] = '5bff9bde1538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bookings_active_status', 'bookings', ['status'], unique=False, postgresql_where=sa.text("status IN ('initiated', 'in_progress')"))
    op.create_index(op.f('ix_bookings_call_unlocked_at'), 'bookings', ['call_unlocked_at'], unique=False)
    op.create_index('ix_bookings_provider_id_created_at', 'bookings', ['provider_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_bookings_seeker_id_created_at', 'bookings', ['seeker_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_user_reports_created_at', 'user_reports', ['created_at', 'id'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_user_reports_created_at', table_name='user_reports')
    op.drop_index('ix_bookings_seeker_id_created_at', table_name='bookings')
    op.drop_index('ix_bookings_provider_id_created_at', table_name='bookings')
    op.drop_index(op.f('ix_bookings_call_unlocked_at'), table_name='bookings')
    op.drop_index('ix_bookings_active_status', table_name='bookings', postgresql_where=sa.text("status IN ('initiated', 'in_progress')"))
    # ### end Alembic commands ###
