"""Indexed seeker_id and added another index on urgent broadcasts status, expires_at

Revision ID: ca688c0d6266
Revises: 1e40abd213da
Create Date: 2026-06-16 14:43:53.807657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca688c0d6266'
down_revision: Union[str, Sequence[str], None] = '1e40abd213da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_urgent_broadcasts_seeker_id'), 'urgent_broadcasts', ['seeker_id'], unique=False)
    op.create_index('ix_urgent_broadcasts_status_expires', 'urgent_broadcasts', ['status', 'expires_at'], unique=False, postgresql_where=sa.text("status = 'BROADCASTING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_urgent_broadcasts_status_expires', table_name='urgent_broadcasts', postgresql_where=sa.text("status = 'BROADCASTING'"))
    op.drop_index(op.f('ix_urgent_broadcasts_seeker_id'), table_name='urgent_broadcasts')
    # ### end Alembic commands ###
