"""added radius_updated_at field

Revision ID: cb875ef25ac9
Revises: 5f0bed00ddd7
Create Date: 2026-06-03 16:22:28.672501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb875ef25ac9'
down_revision: Union[str, Sequence[str], None] = '5f0bed00ddd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('radius_updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'radius_updated_at')
    # ### end Alembic commands ###
