"""removed default NULL for users preferred language

Revision ID: dcb80d4531b7
Revises: 5310b0620353
Create Date: 2026-07-07 20:57:58.808826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb80d4531b7'
down_revision: Union[str, Sequence[str], None] = '5310b0620353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'preferred_lang',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'preferred_lang',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###
