"""alter provider profile enum defaults to lowercase

Revision ID: e1a9f8eae133
Revises: 4406dc965911
Create Date: 2026-05-23 06:42:52.165571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a9f8eae133'
down_revision: Union[str, Sequence[str], None] = '4406dc965911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Dynamically find and drop the check constraint for verification_level
    op.execute("""
        DO $$ 
        DECLARE 
            rname RECORD;
        BEGIN
            FOR rname IN 
                SELECT constraint_name 
                FROM information_schema.constraint_column_usage 
                WHERE table_name = 'provider_profiles' AND column_name = 'verification_level'
            LOOP
                EXECUTE 'ALTER TABLE provider_profiles DROP CONSTRAINT ' || quote_ident(rname.constraint_name);
            END LOOP;
        END $$;
    """)

    # 2. Dynamically find and drop the check constraint for verification_status
    op.execute("""
        DO $$ 
        DECLARE 
            rname RECORD;
        BEGIN
            FOR rname IN 
                SELECT constraint_name 
                FROM information_schema.constraint_column_usage 
                WHERE table_name = 'provider_profiles' AND column_name = 'verification_status'
            LOOP
                EXECUTE 'ALTER TABLE provider_profiles DROP CONSTRAINT ' || quote_ident(rname.constraint_name);
            END LOOP;
        END $$;
    """)

    # 3. Create fresh, predictably-named lowercase constraints
    op.create_check_constraint('check_verification_level', 'provider_profiles',
                               "verification_level IN ('basic', 'verified', 'trusted')")
    op.create_check_constraint('check_verification_status', 'provider_profiles',
                               "verification_status IN ('pending', 'approved', 'rejected')")

    # 4. Update the column server defaults to lowercase strings
    op.alter_column('provider_profiles', 'verification_level',
                    server_default='basic',
                    existing_type=sa.Enum('basic', 'verified', 'trusted', name='verification_level', native_enum=False))

    op.alter_column('provider_profiles', 'verification_status',
                    server_default='pending',
                    existing_type=sa.Enum('pending', 'approved', 'rejected', name='verification_status', native_enum=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop our clean lowercase constraints
    op.drop_constraint('check_verification_level',
                       'provider_profiles', type_='check')
    op.drop_constraint('check_verification_status',
                       'provider_profiles', type_='check')

    # Revert check constraints back to uppercase without worrying about custom names
    op.create_check_constraint('provider_profiles_verification_level_check',
                               'provider_profiles', "verification_level IN ('BASIC', 'VERIFIED', 'TRUSTED')")
    op.create_check_constraint('provider_profiles_verification_status_check',
                               'provider_profiles', "verification_status IN ('PENDING', 'APPROVED', 'REJECTED')")

    # Revert server defaults back to uppercase
    op.alter_column('provider_profiles', 'verification_status',
                    server_default='PENDING',
                    existing_type=sa.Enum('BASIC', 'VERIFIED', 'TRUSTED', name='verification_status', native_enum=False))

    op.alter_column('provider_profiles', 'verification_level',
                    server_default='BASIC',
                    existing_type=sa.Enum('BASIC', 'VERIFIED', 'TRUSTED', name='verification_level', native_enum=False))
    # ### end Alembic commands ###
