"""added nid_url_back

Revision ID: ec8feeca98b1
Revises: cb875ef25ac9
Create Date: 2026-06-04 15:47:09.999751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8feeca98b1'
down_revision: Union[str, Sequence[str], None] = 'cb875ef25ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('nid_url_front', sa.String(), nullable=True))
    op.add_column('provider_profiles', sa.Column('nid_url_back', sa.String(), nullable=True))
    op.drop_column('provider_profiles', 'nid_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('nid_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('provider_profiles', 'nid_url_back')
    op.drop_column('provider_profiles', 'nid_url_front')
    # ### end Alembic commands ###
